services:
  postgres:
    image: postgres:16
    container_name: currency-analyzer-postgres
    environment:
      POSTGRES_DB: currency_analyzer
      POSTGRES_USER: currency_user
      POSTGRES_PASSWORD: currency_password
    ports:
      - "5432:5432"
    volumes:
      - currency_analyzer_postgres_data:/var/lib/postgresql/data

volumes:
  currency_analyzer_postgres_data: