server:
  address: 0.0.0.0
  port: ${PORT:8080}

spring:
  application:
    name: currency-analyzer

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/currency_analyzer}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:currency_user}
    password: ${SPRING_DATASOURCE_PASSWORD:currency_password}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  h2:
    console:
      enabled: false

app:
  security:
    username: ${APP_USERNAME:user}
    password: ${APP_PASSWORD:password}

  exchange-rate:
    base-url: ${EXCHANGE_RATE_BASE_URL:https://api.exchangerate.host}
    access-key: ${EXCHANGE_RATE_API_KEY:}